### PR TITLE
Updated settings.ts and README

### PR DESCRIPTION
**Pull request by asimons04**
PR to add support for features requested in issue #108

I wasn't clear on what "newComments" setting does, if anything, so I didn't add a variable import for that.

I also did not implement env var settings for the `notifications` options as those may or may not be implemented.

### CODE REVIEW

**Review by Xyphyn — APPROVED** [review]
Looks good to me

**Comment by Xyphyn** [comment]
newComments and notifications are unused, so you don't have to do anything for those, you were correct.

**Comment by asimons04** [comment]
Ok, awesome. Wasn't sure at all for `newComments` and figured notifications were probably an in-development feature and may change significantly.  If either of those change later, I can double back and add config imports for them if needed.

I'll have a new PR for one more env var option to set the default theme. Took me a while to figure that one out.   It would conflict with this PR since I'll need to add it to the README.md.  

Once this one is merged, I'll re-base that branch and submit the PR.

**Comment by Xyphyn** [comment]
The default theme is evaluated in `src/app.html` and `src/lib/ui/colors.ts`.

**Pull request merged**
