### PR TITLE
feat: add ability to paste images to post url input when posting

### PR DESCRIPTION
**Pull request by mazury**

### CODE REVIEW

**Comment by Xyphyn** [comment]
this was already added in v1.28.0

**Comment by mazury** [comment]
Are you sure? It's not pasting into comment or post editor, it's pasting into text input where url is pasted. Just like lemmy ui does it.

**Comment by mazury** [comment]
Have you considered that? Here is how it works:

[Screencast from 09.03.2024 09:28:05.webm](https://github.com/Xyphyn/photon/assets/24698150/f80caa28-bfbf-4c02-afc2-7ccc273c94b2)

**Comment by Xyphyn** [comment]
I see what you mean now

**Comment by mazury** [comment]
Yes I created new MR https://github.com/Xyphyn/photon/pull/277, had to change my git flow a bit.

**Pull request closed without merging**
