### PR TITLE
WIP: Infinite scrolling

### PR DESCRIPTION
**Pull request by sant0s12**
This pull requests is a WIP implementation of infinite scrolling.

It seems to work fine in my limited testing except when browsing the home page with no url parameters. In this case, the new page loads and the already existing posts are no longer visible.

I'd also like to implement a spinner to let the user know that new content is being loaded, as well as removing the "next" button since it would no longer be necessary.

In case you don't like the approach that I used to implement this, let me know and I can perhaps try something else or maybe you can tackle this yourself in the future.

Also I kinda goofed the commits with the auto formatter, I hope that is not a big issue. If it is, I can try to un-goof it.

### CODE REVIEW

**Comment by Xyphyn** [comment]
There seems to be a lot of formatting changes, could you make your formatter use my .prettierrc?

**Comment by Xyphyn** [comment]
The only issue with this is what caused me to not implement infinite scroll in the first place- try going to a post, then go back. You lose your place.

I have an idea for implementing infinite scroll, and I will try it tomorrow.

**Comment by sant0s12** [comment]
I think retaining the place works now but it feels like a bit of a hack. Ideally loading posts should be done entirely client side probably.

Another thing is that browsing communities or user profiles don't work yet.

I haven't found a .prettierrc anywhere :(

**Comment by Xyphyn** [comment]
Infinite scroll has been added to Photon now

**Pull request closed without merging**
