### PR TITLE
Allow instance admins access to the "Moderation" menu for federated posts/comments

### PR DESCRIPTION
**Pull request by asimons04**
This PR removes the check for whether a community is local before showing moderation options to instance admins.

## Purpose/Rationale

In the main Lemmy UI, instance admins have full moderation control over remote content as far as their instance is concerned.  They can lock, unlock, remove content, community-ban a user, and pin posts to their local copy of the community.  While these only affect the local instance, they are important moderation abilities.

This allows instance admins to respond to reports from users of their instance when the reported content is from a federated instance (spam, NSFW, local instance rule violation, etc).  This is especially helpful when the remote admin/moderator is slow to respond to reports or if the content violates a local server rule but doesn't violate a rule on the originating instance.  Again, the main Lemmy UI and API support this, so it would only be bringing Photon further to feature parity.

Currently, only Purge is shown for instance admins when the content is on a remote instance.  The problem with "Purge" is that it does exactly what it says: purges the item from the database completely and forgets it ever saw it.

If someone on a federated instance, which still sees the content, votes or comments on it, it will re-sync to the local instance and re-appear in the feed/post.  "Remove", which is only a moderation action, will prevent the content from re-syncing.

I am running this change on my customized build and have tested as such:

### Tests Performed
1. The project successfully builds with this change.
2. Admin user does have moderation options enabled and all work (haven't tested 'Ban from Community' but if it's just calling the API and works already for moderators, then it should work for an admin as well since the API allows that).
3. Logging in as a moderator user has no additional options shown in mod menu nor do they see a moderator button where they shouldn't.
4. Logged-out and unprivileged users see no moderator button at all.

Thoughts?

### CODE REVIEW

**Comment by Xyphyn** [comment]
Good idea. Could you make it so that the check, instead of hiding the menu, will add some text to the "Moderation" text so it says "Moderation (Instance only)"?

**Comment by asimons04** [comment]
> Good idea. Could you make it so that the check, instead of hiding the menu, will add some text to the "Moderation" text so it says "Moderation (Instance only)"?

I think the check you have to show/hide the moderation options works, and I'm hesitant to make too significant of a change to it (especially given my relatively limited experience with Svelte).  

Would keeping the existing logic in place and conditionally setting the Moderation heading text in the menu work for you?

Something like:

```
{#if $profile?.user && $profile.user.local_user_view.person.id != item.creator.id }

    <span class="px-4 py-1 my-1 text-xs text-slate-600 dark:text-zinc-400">
        {#if (item.community.local) }
            Moderation
        {:else}
            Moderation (Instance Only)
        {/if}
    </span>
...
```

I tested it with my instance, and that worked. Local communities showed "Moderation" on the menu heading while remote communities showed "Moderation (Instance Only)"

**Local Community Post**
image

**Federated Post**
image


If you're good with that, I can finalize that (and do the same for the User heading and the same for the CommentModerationMenu).

**Comment by Xyphyn** [comment]
That's what I wanted. Thanks a lot!

**Comment by asimons04** [comment]
> That's what I wanted. Thanks a lot!

Perfect.  Give me a few to implement that in my branch, build, test, and push up the changes.

**Comment by asimons04** [comment]
Tested and pushed to the branch for this PR.

**Comment by Xyphyn** [comment]
Thanks for your contribution!

**Pull request merged**
