### PR TITLE
Add some password length info for user

### PR DESCRIPTION
**Pull request by gapetto**

### CODE REVIEW

**Comment by Xyphyn** [comment]
It'd be better if the password was just invalidated under 10 characters, as this would get the point across while using the browser's tools. Don't worry about it- i'll add this, and will credit you in the upcoming release for bring this to my attention.

**Comment by gapetto** [comment]
@Xyphyn this is still an issue - I think users may not notice the popup in the right bottom corner as in current state, they'll think that something is broken and eventually they just give up signing up.

**Comment by Xyphyn** [comment]
I set a minlength and the popup will appear directly under the password input, and the password would be red.

**Comment by gapetto** [comment]
Sounds good as long as it's clearly visible. My user counter hasn't moved a lot for a long time and I just wonder how much of a factor this is.

**Pull request closed without merging**
